// examples/svelte/src/App.svelte
<script>
  import Box from "./components/Box.svelte";
  import Button from "./components/Button.svelte";
  import ToggleTheme from "./components/ToggleTheme.svelte";
</script>

<Box bg="background" flexDirection="row" justifyContent="space-evenly" alignItems="center">
  <ToggleTheme />
  <Button variant="primary">Primary</Button>
  <Button variant="round">Round</Button>
</Box>

// apps/web-sandbox/src/App.tsx
import { theme, Component, Variant, useStyles } from '@morfeo/react';
import { Box, Button, Typography, ThemeToggle } from './components';

function getStyle<C extends Component = Component>(
  component: C,
  variant?: Variant<C>,
) {
  // @ts-ignore
  const { style, tag, props, variants } = theme.getValue(
    'components',
    component,
  );
  // @ts-ignore
  if (variant && variants && variants[variant]) {
    // @ts-ignore
    return JSON.stringify(variants[variant], undefined, 2);
  }

  return JSON.stringify({ style, tag, props }, undefined, 2);
}

function App() {
  const { containerStyle, blockStyle, codeStyle } = useStyles({
    containerStyle: {
      bg: 'background',
      width: '100%' as any,
      display: 'flex',
      minHeight: '100vh' as any,
      alignItems: 'center',
      justifyContent: 'space-evenly',
      transition: 'slow',
      pt: 's',
      pb: 's',
    },
    blockStyle: {
      flex: 1,
      display: 'flex',
      flexDirection: 'column',
      alignItems: 'center',
      justifyContent: 'space-evenly',
      height: '100%' as any,
    },
    codeStyle: {
      display: 'block',
      py: 's',
    },
  });

  return (
    <Box style={containerStyle}>
      <Box style={blockStyle}>
        <ThemeToggle />
        <Typography variant="code" style={codeStyle}>
          {getStyle('Button')}
        </Typography>
      </Box>
      <Box style={blockStyle}>
        <Button variant="primary">Primary variant</Button>
        <Typography variant="code" style={codeStyle}>
          {getStyle('Button', 'primary')}
        </Typography>
      </Box>
      <Box style={blockStyle}>
        <Button variant="round">Round variant</Button>
        <Typography variant="code" style={codeStyle}>
          {getStyle('Button', 'round')}
        </Typography>
      </Box>
    </Box>
  );
}

export default App;
